// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dropbox_backend.Data;

#nullable disable

namespace dropbox_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306072144_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dropbox_backend.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InsideFiles")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SharedUsersCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsideFiles = 3985,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "Documents",
                            SharedUsersCount = 86
                        },
                        new
                        {
                            Id = 2,
                            InsideFiles = 499,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "Music",
                            SharedUsersCount = 85
                        },
                        new
                        {
                            Id = 3,
                            InsideFiles = 256,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "ProjectK",
                            SharedUsersCount = 0
                        },
                        new
                        {
                            Id = 4,
                            InsideFiles = 1225,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "Rico Media",
                            SharedUsersCount = 52
                        },
                        new
                        {
                            Id = 5,
                            InsideFiles = 2265,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "New Dev",
                            SharedUsersCount = 22
                        },
                        new
                        {
                            Id = 6,
                            InsideFiles = 597,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "Files 2022",
                            SharedUsersCount = 12
                        });
                });

            modelBuilder.Entity("dropbox_backend.Models.RecentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SharedUsersCount")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RecentFiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "assets/icons/icon-file-image.svg",
                            ModifiedDate = "Dec 13, 2022",
                            Name = "Website Design.png",
                            SharedUsersCount = 12,
                            Size = "2.8 MB",
                            Type = "image"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "assets/icons/icon-folder.svg",
                            ModifiedDate = "Dec 12, 2022",
                            Name = "UX-UI.zip",
                            SharedUsersCount = 5,
                            Size = "242 MB",
                            Type = "archive"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "assets/icons/icon-video.svg",
                            ModifiedDate = "Dec 12, 2022",
                            Name = "Office.mp4",
                            SharedUsersCount = 0,
                            Size = "1.8 GB",
                            Type = "video"
                        });
                });

            modelBuilder.Entity("dropbox_backend.Models.StorageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Percentage")
                        .HasColumnType("integer");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Used")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Storage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Percentage = 75,
                            Total = 800,
                            Unit = "GB",
                            Used = 600
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
