// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dropbox_backend.Data;

#nullable disable

namespace dropbox_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dropbox_backend.Models.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InsideFiles")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SharedUsersCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsideFiles = 3985,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "Documents",
                            SharedUsersCount = 86
                        },
                        new
                        {
                            Id = 2,
                            InsideFiles = 499,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "Music",
                            SharedUsersCount = 85
                        },
                        new
                        {
                            Id = 3,
                            InsideFiles = 256,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "ProjectK",
                            SharedUsersCount = 0
                        },
                        new
                        {
                            Id = 4,
                            InsideFiles = 1225,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "Rico Media",
                            SharedUsersCount = 52
                        },
                        new
                        {
                            Id = 5,
                            InsideFiles = 2265,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "New Dev",
                            SharedUsersCount = 22
                        },
                        new
                        {
                            Id = 6,
                            InsideFiles = 597,
                            ModifiedDate = "Sep 25, 2022, 13:25 PM",
                            Name = "Files 2022",
                            SharedUsersCount = 12
                        });
                });

            modelBuilder.Entity("dropbox_backend.Models.NavigationItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Navigations");

                    b.HasData(
                        new
                        {
                            Id = "home",
                            Icon = "assets/icons/icon-home.svg",
                            Label = "Home",
                            Order = 1
                        },
                        new
                        {
                            Id = "my-files",
                            Icon = "assets/icons/icon-my-files.svg",
                            Label = "My Files",
                            Order = 2
                        },
                        new
                        {
                            Id = "starred",
                            Icon = "assets/icons/icon-starred.svg",
                            Label = "Starred",
                            Order = 3
                        },
                        new
                        {
                            Id = "shared",
                            Icon = "assets/icons/icon-shared.svg",
                            Label = "Shared",
                            Order = 4
                        },
                        new
                        {
                            Id = "file-requests",
                            Icon = "assets/icons/icon-file-requests.svg",
                            Label = "Files Requests",
                            Order = 5
                        },
                        new
                        {
                            Id = "deleted",
                            Icon = "assets/icons/icon-deleted.svg",
                            Label = "Deleted",
                            Order = 6
                        });
                });

            modelBuilder.Entity("dropbox_backend.Models.RecentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SharedUsersCount")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RecentFiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "assets/icons/icon-file-image.svg",
                            ModifiedDate = "Dec 13, 2022",
                            Name = "Website Design.png",
                            SharedUsersCount = 12,
                            Size = "2.8 MB",
                            Type = "image"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "assets/icons/icon-folder.svg",
                            ModifiedDate = "Dec 12, 2022",
                            Name = "UX-UI.zip",
                            SharedUsersCount = 5,
                            Size = "242 MB",
                            Type = "archive"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "assets/icons/icon-video.svg",
                            ModifiedDate = "Dec 12, 2022",
                            Name = "Office.mp4",
                            SharedUsersCount = 0,
                            Size = "1.8 GB",
                            Type = "video"
                        });
                });

            modelBuilder.Entity("dropbox_backend.Models.SharedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FolderId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RecentFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("RecentFileId");

                    b.ToTable("SharedUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "assets/avatars/avatar-1.png",
                            FolderId = 1,
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "assets/avatars/avatar-2.png",
                            FolderId = 1,
                            Name = "User 2"
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "assets/avatars/avatar-3.png",
                            FolderId = 1,
                            Name = "User 3"
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "assets/avatars/avatar-4.png",
                            FolderId = 1,
                            Name = "User 4"
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "assets/avatars/avatar-1.png",
                            FolderId = 1,
                            Name = "User 5"
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "assets/avatars/avatar-2.png",
                            FolderId = 1,
                            Name = "User 6"
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "assets/avatars/avatar-1.png",
                            FolderId = 2,
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 8,
                            Avatar = "assets/avatars/avatar-2.png",
                            FolderId = 2,
                            Name = "User 2"
                        },
                        new
                        {
                            Id = 9,
                            Avatar = "assets/avatars/avatar-3.png",
                            FolderId = 2,
                            Name = "User 3"
                        },
                        new
                        {
                            Id = 10,
                            Avatar = "assets/avatars/avatar-4.png",
                            FolderId = 2,
                            Name = "User 4"
                        },
                        new
                        {
                            Id = 11,
                            Avatar = "assets/avatars/avatar-1.png",
                            FolderId = 2,
                            Name = "User 5"
                        },
                        new
                        {
                            Id = 12,
                            Avatar = "assets/avatars/avatar-2.png",
                            FolderId = 2,
                            Name = "User 6"
                        },
                        new
                        {
                            Id = 13,
                            Avatar = "assets/avatars/avatar-1.png",
                            FolderId = 3,
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 14,
                            Avatar = "assets/avatars/avatar-2.png",
                            FolderId = 3,
                            Name = "User 2"
                        },
                        new
                        {
                            Id = 15,
                            Avatar = "assets/avatars/avatar-3.png",
                            FolderId = 3,
                            Name = "User 3"
                        },
                        new
                        {
                            Id = 16,
                            Avatar = "assets/avatars/avatar-1.png",
                            FolderId = 4,
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 17,
                            Avatar = "assets/avatars/avatar-2.png",
                            FolderId = 4,
                            Name = "User 2"
                        },
                        new
                        {
                            Id = 18,
                            Avatar = "assets/avatars/avatar-3.png",
                            FolderId = 4,
                            Name = "User 3"
                        },
                        new
                        {
                            Id = 19,
                            Avatar = "assets/avatars/avatar-4.png",
                            FolderId = 4,
                            Name = "User 4"
                        },
                        new
                        {
                            Id = 20,
                            Avatar = "assets/avatars/avatar-1.png",
                            FolderId = 5,
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 21,
                            Avatar = "assets/avatars/avatar-2.png",
                            FolderId = 5,
                            Name = "User 2"
                        },
                        new
                        {
                            Id = 22,
                            Avatar = "assets/avatars/avatar-3.png",
                            FolderId = 5,
                            Name = "User 3"
                        },
                        new
                        {
                            Id = 23,
                            Avatar = "assets/avatars/avatar-4.png",
                            FolderId = 5,
                            Name = "User 4"
                        },
                        new
                        {
                            Id = 24,
                            Avatar = "assets/avatars/avatar-1.png",
                            FolderId = 6,
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 25,
                            Avatar = "assets/avatars/avatar-2.png",
                            FolderId = 6,
                            Name = "User 2"
                        },
                        new
                        {
                            Id = 26,
                            Avatar = "assets/avatars/avatar-3.png",
                            FolderId = 6,
                            Name = "User 3"
                        },
                        new
                        {
                            Id = 27,
                            Avatar = "assets/avatars/avatar-1.png",
                            Name = "User 1",
                            RecentFileId = 1
                        },
                        new
                        {
                            Id = 28,
                            Avatar = "assets/avatars/avatar-2.png",
                            Name = "User 2",
                            RecentFileId = 1
                        },
                        new
                        {
                            Id = 29,
                            Avatar = "assets/avatars/avatar-3.png",
                            Name = "User 3",
                            RecentFileId = 1
                        },
                        new
                        {
                            Id = 30,
                            Avatar = "assets/avatars/avatar-4.png",
                            Name = "User 4",
                            RecentFileId = 1
                        },
                        new
                        {
                            Id = 31,
                            Avatar = "assets/avatars/avatar-1.png",
                            Name = "User 5",
                            RecentFileId = 1
                        },
                        new
                        {
                            Id = 32,
                            Avatar = "assets/avatars/avatar-2.png",
                            Name = "User 6",
                            RecentFileId = 1
                        },
                        new
                        {
                            Id = 33,
                            Avatar = "assets/avatars/avatar-1.png",
                            Name = "User 1",
                            RecentFileId = 2
                        },
                        new
                        {
                            Id = 34,
                            Avatar = "assets/avatars/avatar-2.png",
                            Name = "User 2",
                            RecentFileId = 2
                        },
                        new
                        {
                            Id = 35,
                            Avatar = "assets/avatars/avatar-3.png",
                            Name = "User 3",
                            RecentFileId = 2
                        },
                        new
                        {
                            Id = 36,
                            Avatar = "assets/avatars/avatar-4.png",
                            Name = "User 4",
                            RecentFileId = 2
                        },
                        new
                        {
                            Id = 37,
                            Avatar = "assets/avatars/avatar-1.png",
                            Name = "User 5",
                            RecentFileId = 2
                        },
                        new
                        {
                            Id = 38,
                            Avatar = "assets/avatars/avatar-1.png",
                            Name = "User 1",
                            RecentFileId = 3
                        },
                        new
                        {
                            Id = 39,
                            Avatar = "assets/avatars/avatar-2.png",
                            Name = "User 2",
                            RecentFileId = 3
                        });
                });

            modelBuilder.Entity("dropbox_backend.Models.StorageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Percentage")
                        .HasColumnType("integer");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Used")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Storage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Percentage = 75,
                            Total = 800,
                            Unit = "GB",
                            Used = 600
                        });
                });

            modelBuilder.Entity("dropbox_backend.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "assets/avatars/avatar-1.png",
                            Name = "James Alto"
                        });
                });

            modelBuilder.Entity("dropbox_backend.Models.SharedUser", b =>
                {
                    b.HasOne("dropbox_backend.Models.Folder", null)
                        .WithMany("SharedUsers")
                        .HasForeignKey("FolderId");

                    b.HasOne("dropbox_backend.Models.RecentFile", null)
                        .WithMany("SharedUsers")
                        .HasForeignKey("RecentFileId");
                });

            modelBuilder.Entity("dropbox_backend.Models.Folder", b =>
                {
                    b.Navigation("SharedUsers");
                });

            modelBuilder.Entity("dropbox_backend.Models.RecentFile", b =>
                {
                    b.Navigation("SharedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
